services:
  database:
    image: mongo:8.0.6
    container_name: database
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./.volumes/mongodb:/data/db
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - tfm_network
    restart: always

  backend:
    container_name: cyberattacks_backend
    build: ./backend/
    image: cyberattacks_backend
    env_file:
      - ./.env
    ports:
      - 8080:8080
    networks:
      - tfm_network
    depends_on:
      - database
    restart: always

networks:
  tfm_network:
