services:
  database:
    image: mongo:8.0.6
    container_name: database
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./.volumes/mongodb:/data/db
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - tfm_network
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "-eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    env_file:
      - ./.env
    ports:
      - 8080:8080
    networks:
      - tfm_network
    depends_on:
      database:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    build: ./frontend/
    image: frontend
    ports:
      - 3000:80
    networks:
      - tfm_network
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  tor-proxy:
    image: dperson/torproxy
    container_name: tor-proxy
    volumes:
      - ./tor/torrc:/etc/tor/torrc
    networks:
      - tfm_network
    restart: always
    # healthcheks implemented in base image

  scraper:
    container_name: scraper
    build: ./scraper/
    image: scraper
    volumes:
      - ./.volumes/.scraper:/app/data
    networks:
      - tfm_network
    depends_on:
      tor-proxy:
        condition: service_healthy

  etl:
    container_name: etl
    build: ./etl/
    image: etl
    volumes:
      - ./.volumes/.scraper:/app/data
    networks:
      - tfm_network

networks:
  tfm_network:
